//! Story flags type
use serde::{Deserialize, Serialize};

/// A story flag set during gameplay
///
/// The C# type is `GameVariables.Flag` (`TypeDefIndex`: 1320)
#[cfg_attr(feature = "derive-clone", derive(Clone))]
#[cfg_attr(feature = "derive-debug", derive(Debug))]
#[derive(Serialize, Deserialize)]
pub struct StoryFlags {
    /// Identifier string of the flag
    pub name: String,
    /// In-game minute when the flag was most recently set
    #[serde(rename = "timeAdded")]
    pub time_added: i32,
    /// In-game minute when the flag was set for the very first time
    #[serde(rename = "firstTimeAdded")]
    pub first_time_added: i32,
    /// Total number of times this flag has been set
    pub times: i32,
}

impl StoryFlags {
    /// Creates a new storyflag with `time` as `time_added` and `first_time_added` and 1 as 
    #[must_use] 
    pub const fn new(name: String, time: i32) -> Self {
        Self {
            name,
            time_added: time,
            first_time_added: time,
            times: 1,
        }
    }

    /// Many thanks to brunoais, for finding them
    /// <https://gitlab.com/brunoaiss/mdrg-save-editor/-/blob/master/MDRG-save-editor.py?ref_type=heads#L34>
    pub const KNOWN_FLAGS: &'static [&'static str] = &[
        "AfterFirstFuck",
        "afterRiots_withBot_firstTime",
        "AirPollutionMask",
        "Annalie_afterriots_helped",
        "Annalie_afterriotsWithBot_wentAlone",
        "Annalie_cafe1",
        "Annalie_cafe2",
        "Annalie_gave_money",
        "Annalie_riots_returnedMoney",
        "Annalie_riots1",
        "Annalie_riots2",
        "artgallery1",
        "artgallery2",
        "bigdaddyinvitation",
        "bigDaddysAdviceFinished",
        "Bigdaddystoryline_timer",
        "bigdaddystoryline1",
        "bigdaddystoryline2",
        "bigdaddystoryline3",
        "bigdaddystoryline4",
        "birthday",
        "Blaubeim1-choices112",
        "BlaubeimEventStarted",
        "BlaubeimMedicine",
        "botRaep",
        "bowling1",
        "cards",
        "casino",
        "chess",
        "church-endJustGoThereGood",
        "church-nextDrugiePojscieABA",
        "church-nextRevival",
        "church-nextSpotykaBotaCrash",
        "church-nun_back_visit_timer",
        "church-nun_back1",
        "church-nun_back2",
        "church-whatHappenedAfter",
        "church",
        "clothier1",
        "clothier2",
        "clothier3",
        "clothier4",
        "clothiervisit",
        "coat",
        "cocktractsunlocked",
        "coffee",
        "CustomClothing",
        "dadJoke",
        "date",
        "diarrhea",
        "dinnerwithbigdaddy1",
        "Dispenser_AfterRiots",
        "Dispenser_Riots_FirstTime",
        "Dispenser_Riots_Hobo",
        "dispenserempty24hours",
        "exposure_day",
        "exposure",
        "FedPhoneCall",
        "FirstBotRaepMc",
        "firstClothes",
        "firstdelivery",
        "FirstPayment",
        "firstslowmode",
        "firsttimeflacid",
        "firstwalk",
        "food",
        "GoingOutside1",
        "GoingOutside2",
        "GoingOutside3",
        "good_soul",
        "groceries",
        "Grocery_Riots_FirstTime",
        "hangingOutWithAnnalie",
        "hangingOutWithMelissa",
        "helpedlandlord",
        "hobo_failed",
        "hobo",
        "hobo1",
        "hobo1eventHappened",
        "hobo2",
        "illegalTrash",
        "joinus",
        "JoinUs2",
        "joinusBigDaddy",
        "joinusemail2",
        "joinusemail2opened",
        "JoinUsRegret",
        "Karaoke1",
        "KaraokeTalk",
        "kino1",
        "kinoTalk",
        "LabourOffice_AfterRiots",
        "LabourOffice_Riots_FirstTime",
        "LabourOffice_Riots_Landlord",
        "labouroffice",
        "ladyparts",
        "LandlordConspiracy0",
        "LandlordConspiracy1",
        "LandlordConspiracy2",
        "LandlordConspiracy3",
        "LandlordDaughter1",
        "LandlordMoneyEvent",
        "LandlordStaircase",
        "lastdate",
        "lorerant1",
        "love",
        "Melissa",
        "Melissa1",
        "Melissa2",
        "Melissa3",
        "Melissa4",
        "Melissa4bot",
        "Melissa4Hobo",
        "Melissa5bot",
        "Melissa5Normal",
        "pets1",
        "Pharmacy_AfterRiots",
        "Pharmacy_Riots_FirstTime",
        "Pharmacy_Riots_Random",
        "Priestbot_Mark_1",
        "psychologist1",
        "Question",
        "random_search_1",
        "randomsearch1",
        "randomsearch2",
        "randomsearch3",
        "restaurant1",
        "restaurant2",
        "riots_firstWalk",
        "Riots_reporter",
        "riots_start_event",
        "riots",
        "RiotsBotBringsFood",
        "RiotsEndingSoonNotice",
        "RiotsEndNotice",
        "SleepingWithBotUnlocked",
        "stonks",
        "TalkAboutLandlord1",
        "trashdiving",
        "unlockedslowmode",
        "unlockedslowmodeemail",
        "WalkWithBot",
        "walkwithlandlord",
        "wordchain",
    ];
}
